config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#home'
  get '/portfolio', to: 'pages#portfolio', as: 'portfolio'
  get '/account', to: 'pages#account', as: 'account'
  get '/blocked', to: 'pages#blocked', as: 'blocked'

  get '/transactions', to: 'transactions#index', as: 'transactions'
  get '/cashin', to: 'transactions#cashin', as: 'cashin'
  post '/cashin', to: 'transactions#cashin_post', as: 'cashin_post'
  post '/buy/:id', to: 'transactions#buy', as: 'buy'
  post '/sell/:id', to: 'transactions#sell', as: 'sell'

  get '/users', to: 'users#index', as: 'users'
  get '/pending', to: 'users#pending', as: 'pending'
  get '/users/new', to: 'users#new', as: 'new_user'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  post '/users/create', to: 'users#create', as: 'create_user'
  patch '/users/:id/update', to: 'users#update', as: 'update_user'
  patch '/users/:id/approve', to: 'users#approve', as: 'approve_user'

  get '/stocks', to: 'stocks#index', as: 'stocks'
  get '/stocks/:id', to: 'stocks#show', as: 'stock'
  post '/stocks/create', to: 'stocks#create', as: 'create_stock'
  patch '/stocks/:id/update', to: 'stocks#update', as: 'update_stock'
end

app/models/stock.rb
class Stock < ApplicationRecord
  validates :symbol, presence: true
  validates :price, presence: true
  validates :company, presence: true
  validates :change_percent, presence: true
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :approved_only

  def index
    @stocks = Stock.all.order(:symbol)
    @selected = 'stocks'
  end

  def show
    @stock = Stock.find(params[:id])
    @selected = 'stocks'
  end
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/index.html.erb
<div class='centered-body'>
  <div class='header'>Stocks</div>
  <% if @stocks.length > 0 %>
    <div class='card'>
      <table>
        <tr>
          <th>Symbol</th>
          <th>Price</th>
          <th>Change</th>
          <th>Company</th>
          <th class='centered-cell'>Trade</th>
        </tr>
        <% @stocks.each do |stock| %>
          <tr>
            <td>
              <%= stock.symbol %>
            </td>
            <td>
              <% if stock.change_percent >= 0 %>
                <div class='green'>
                  <%= number_to_currency(stock.price, format: '%u %n') %>
                </div>
              <% else %>
                <div class='red'>
                  <%= number_to_currency(stock.price, format: '%u %n') %>
                </div>
              <% end %>
            </td>
            <td>
              <% if stock.change_percent >= 0 %>
                <div class='green'>
                  <%= "+ #{(stock.change_percent * 100).round(2)}%" %>
                </div>
              <% else %>
                <div class='red'>
                  <%= "- #{(stock.change_percent * 100).abs.round(2)}%" %>
                </div>
              <% end %>
            </td>
            <td>
              <%= stock.company %>
            </td>
            <td class='cell-with-centered-image'>
              <%= link_to stock_path(stock) do %>
                <%= image_tag('trade.svg') %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  <% else %>
    <%= render 'pages/empty' %>
  <% end %>
</div>

app/views/stocks/show.html.erb
<div class='centered-body'>
  <%= link_to stocks_path do %>
    <%= image_tag('back.svg') %>
  <% end %>
  <div class='card flex-column-5px-gap'>
    <div class='stock-name'>
      <%= @stock.symbol %>
    </div>
    <div class='stock-price'>
      <% if @stock.change_percent >= 0 %>
        <div class='green'>
          <%= number_to_currency(@stock.price, format: '%u %n') %>
        </div>
      <% else %>
        <div class='red'>
          <%= number_to_currency(@stock.price, format: '%u %n') %>
        </div>
      <% end %>
    </div>
    <div class='stock-change-percent'>
      <% if @stock.change_percent >= 0 %>
        <div class='green'>
          <%= "+ #{(@stock.change_percent * 100).round(2)}%" %>
        </div>
      <% else %>
        <div class='red'>
          <%= "- #{(@stock.change_percent * 100).abs.round(2)}%" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class='split-card'>
    <div class='card flex-column-10px-gap'>
      <div class='header'>Buy</div>
      <%= form_with model: current_user.transactions.new, url: buy_path(@stock.id) do |f| %>
        <div class='flex-column-20px-gap'>
          <div>
            <%= f.label :quantity %>
            <%= f.number_field :quantity %>
          </div>
          <div>
            <%= f.submit 'Buy stock', class: 'button-primary' %>
          </div>
        </div>
      <% end %>
    </div>
    <div class='card flex-column-10px-gap'>
      <div class='header'>Sell</div>
      <%= form_with model: current_user.transactions.new, url: sell_path(@stock.id) do |f| %>
        <div class='flex-column-20px-gap'>
          <div>
            <%= f.label :quantity %>
            <%= f.number_field :quantity %>
          </div>
          <div>
            <%= f.submit 'Sell stock', class: 'button-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>