config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#home'
  get '/portfolio', to: 'pages#portfolio', as: 'portfolio'
  get '/account', to: 'pages#account', as: 'account'
  get '/blocked', to: 'pages#blocked', as: 'blocked'

  get '/transactions', to: 'transactions#index', as: 'transactions'
  get '/cashin', to: 'transactions#cashin', as: 'cashin'
  post '/cashin', to: 'transactions#cashin_post', as: 'cashin_post'
  post '/buy/:id', to: 'transactions#buy', as: 'buy'
  post '/sell/:id', to: 'transactions#sell', as: 'sell'

  get '/users', to: 'users#index', as: 'users'
  get '/pending', to: 'users#pending', as: 'pending'
  get '/users/new', to: 'users#new', as: 'new_user'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  post '/users/create', to: 'users#create', as: 'create_user'
  patch '/users/:id/update', to: 'users#update', as: 'update_user'
  patch '/users/:id/approve', to: 'users#approve', as: 'approve_user'

  get '/stocks', to: 'stocks#index', as: 'stocks'
  get '/stocks/:id', to: 'stocks#show', as: 'stock'
  post '/stocks/create', to: 'stocks#create', as: 'create_stock'
  patch '/stocks/:id/update', to: 'stocks#update', as: 'update_stock'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  has_many :transactions, dependent: :destroy
  validates :first_name,
            presence: true,
            uniqueness: {
              scope: :last_name,
              message:
                'and last name combination already belongs to an existing user',
            }
  validates :last_name, presence: true

  after_create :after_create
  after_update :approved_email

  private

  def after_create
    welcome_email
    new_user_email
  end

  def welcome_email
    if self.admin == false
      UserMailer.with(user: self).welcome_email.deliver_later
    end
  end

  def new_user_email
    if self.admin == false
      UserMailer.with(user: self).new_user_email.deliver_later
    end
  end

  def approved_email
    if self.approved_previously_was == false && self.approved == true
      UserMailer.with(user: self).approved_email.deliver_later
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[show edit update]
  before_action :admin_only
  before_action :approved_only

  def index
    @users = User.all.order(created_at: :desc)
    @selected = 'users'
  end

  def pending
    @users = User.all.order(:created_at).where(approved: false)
    @selected = 'pending'
  end

  def show
    #
    @selected = 'users'
  end

  def new
    @user = User.new
    @selected = 'users'
  end

  def create
    @user = User.new(user_params.merge(approved: true))

    if @user.save
      UserMailer.with(user: @user).approved_email.deliver_later
      redirect_to users_path, notice: 'Created user'
    else
      render :new
    end
  end

  def edit
    #
    @selected = 'users'
  end

  def update
    params = user_params.clone

    if params[:password].length == 0 &&
         params[:password_confirmation].length == 0
      params[:password] = @user.password
      params[:password_confirmation] = @user.password
    end

    if @user.update(params)
      redirect_to users_path, notice: 'Updated user'
    else
      render :edit
    end
  end

  def approve
    @user = User.find(params[:id])
    @user.update(approved: true)
    redirect_to users_path, notice: 'Approved user'
  end

  private

  def user_params
    params
      .require(:user)
      .permit(
        :first_name,
        :last_name,
        :email,
        :password,
        :password_confirmation,
      )
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class='card flex-column-10px-gap'>
  <div class='header'>
    <%= header %>
  </div>
  <%= form_with model: user, url: path do |f| %>
    <div class='flex-column-20px-gap'>
      <div class='flex-column-5px-gap'>
        <div>
          <%= f.label :email %>
          <%= f.email_field :email, autofocus: true %>
        </div>
        <% @user.errors.full_messages_for(:email).each do |message| %>
          <div class='error-message'>
            <%= message %>
          </div>
        <% end %>
      </div>
      <div class='flex-column-5px-gap'>
        <div>
          <%= f.label :first_name %>
          <%= f.text_field :first_name %>
        </div>
        <% @user.errors.full_messages_for(:first_name).each do |message| %>
          <div class='error-message'>
            <%= message %>
          </div>
        <% end %>
      </div>
      <div class='flex-column-5px-gap'>
        <div>
          <%= f.label :last_name %>
          <%= f.text_field :last_name %>
        </div>
        <% @user.errors.full_messages_for(:last_name).each do |message| %>
          <div class='error-message'>
            <%= message %>
          </div>
        <% end %>
      </div>
      <div class='flex-column-5px-gap'>
        <div>
          <%= f.label :password %>
        </div>
        <%= f.password_field :password %>
        <% @user.errors.full_messages_for(:password).each do |message| %>
          <div class='error-message'>
            <%= message %>
          </div>
        <% end %>
      </div>
      <div class='flex-column-5px-gap'>
        <div>
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation %>
        </div>
        <% @user.errors.full_messages_for(:password_confirmation).each do |message| %>
          <div class='error-message'>
            <%= message %>
          </div>
        <% end %>
      </div>
      <div>
        <%= f.submit button_text, class: 'button-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='centered-body'>
  <%= link_to users_path do %>
    <%= image_tag('back.svg') %>
  <% end %>
  <%= render 'form', user: @user, path: update_user_path(@user), button_text: 'Update user', header: 'Edit user' %>
</div>

app/views/users/index.html.erb
<div class='centered-body'>
  <div class='flex-space-between'>
    <div class='header'>Users</div>
    <%= link_to 'New user', new_user_path, class: 'button-primary' %>
  </div>
  <% if @users.length > 0 %>
    <div class='card'>
      <table>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th class='centered-cell'>Approved</th>
          <th class='centered-cell'>Show</th>
          <th class='centered-cell'>Edit</th>
        </tr>
        <% @users.all.each do |user| %>
          <tr>
            <td>
              <%= "#{user.first_name} #{user.last_name}" %>
            </td>
            <td>
              <%= user.email %>
            </td>
            <td class='cell-with-centered-image'>
              <% if user.approved %>
                <%= image_tag('yes.svg') %>
              <% else %>
                <%= image_tag('no.svg') %>
              <% end %>
            </td>
            <td class='cell-with-centered-image'>
              <%= link_to user_path(user) do %>
                <%= image_tag('show.svg') %>
              <% end %>
            </td>
            <td class='cell-with-centered-image'>
              <%= link_to edit_user_path(user) do %>
                <%= image_tag('edit.svg') %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  <% else %>
    <%= render 'pages/empty' %>
  <% end %>
</div>

app/views/users/new.html.erb
<div class='centered-body'>
  <%= link_to users_path do %>
    <%= image_tag('back.svg') %>
  <% end %>
  <%= render 'form', user: @user, path: create_user_path, button_text: 'Create user', header: 'New user' %>
</div>

app/views/users/pending.html.erb
<div class='centered-body'>
  <div class='header'>Pending</div>
  <% if @users.length > 0 %>
    <div class='card'>
      <table>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th class='centered-cell'>Approve</th>
        </tr>
        <% @users.all.each do |user| %>
          <tr>
            <td>
              <%= "#{user.first_name} #{user.last_name}" %>
            </td>
            <td>
              <%= user.email %>
            </td>
            <td class='cell-with-centered-image'>
              <%= link_to approve_user_path(user), method: 'patch' do %>
                <%= image_tag('approve.svg') %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  <% else %>
    <%= render 'pages/empty' %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class='centered-body'>
  <%= link_to users_path do %>
    <%= image_tag('back.svg') %>
  <% end %>
  <div class='header'>
    <%= "#{@user.first_name} #{@user.last_name}" %>
  </div>
  <div class='card'>
    <table>
      <tr>
        <td class='gray'>
          First name
        </td>
        <td>
          <%= @user.first_name %>
        </td>
      </tr>
      <tr>
        <td class='gray'>
          Last name
        </td>
        <td>
          <%= @user.last_name %>
        </td>
      </tr>
      <tr>
        <td class='gray'>
          Email
        </td>
        <td>
          <%= @user.email %>
        </td>
      </tr>
      <tr>
        <td class='gray'>
          Approved
        </td>
        <td>
          <% if @user.approved %>
            <%= image_tag('yes.svg') %>
          <% else %>
            <%= image_tag('no.svg') %>
          <% end %>
        </td>
      </tr>
      <tr>
        <td class='gray'>
          Admin
        </td>
        <td>
          <% if @user.admin %>
            <%= image_tag('yes.svg') %>
          <% else %>
            <%= image_tag('no.svg') %>
          <% end %>
        </td>
      </tr>
    </table>
  </div>
</div>