config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#home'
  get '/portfolio', to: 'pages#portfolio', as: 'portfolio'
  get '/account', to: 'pages#account', as: 'account'
  get '/blocked', to: 'pages#blocked', as: 'blocked'

  get '/transactions', to: 'transactions#index', as: 'transactions'
  get '/cashin', to: 'transactions#cashin', as: 'cashin'
  post '/cashin', to: 'transactions#cashin_post', as: 'cashin_post'
  post '/buy/:id', to: 'transactions#buy', as: 'buy'
  post '/sell/:id', to: 'transactions#sell', as: 'sell'

  get '/users', to: 'users#index', as: 'users'
  get '/pending', to: 'users#pending', as: 'pending'
  get '/users/new', to: 'users#new', as: 'new_user'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  post '/users/create', to: 'users#create', as: 'create_user'
  patch '/users/:id/update', to: 'users#update', as: 'update_user'
  patch '/users/:id/approve', to: 'users#approve', as: 'approve_user'

  get '/stocks', to: 'stocks#index', as: 'stocks'
  get '/stocks/:id', to: 'stocks#show', as: 'stock'
  post '/stocks/create', to: 'stocks#create', as: 'create_stock'
  patch '/stocks/:id/update', to: 'stocks#update', as: 'update_stock'
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_balance, only: %i[buy]
  before_action :set_portfolio, only: %i[sell]
  before_action :trader_only, except: %i[index]
  before_action :approved_only

  def index
    if current_user.admin
      @transactions = Transaction.all.order(created_at: :desc)
    else
      @transactions =
        Transaction.where(user_id: current_user.id).order(created_at: :desc)
    end
    @selected = 'transactions'
  end

  def cashin
    @transaction = current_user.transactions.new
    @selected = 'account'
  end

  def cashin_post
    @transaction =
      current_user.transactions.new(transaction_params.merge(action: 'cash in'))

    if @transaction.save
      redirect_to account_path, notice: 'Cashed in'
    else
      render :cashin
    end
  end

  def buy
    stock = Stock.find(params[:id])
    quantity = params[:transaction][:quantity].to_i
    amount = stock.price * quantity
    if quantity > 0
      if amount < @balance
        @transaction =
          current_user.transactions.new(
            transaction_params.merge(
              action: 'purchase',
              stock_id: stock.id,
              price: stock.price,
              amount: amount * -1,
            ),
          )

        if @transaction.save
          redirect_to stock_path(stock.id), notice: 'Purchased stock'
        else
          redirect_to stock_path(stock.id), alert: 'Error'
        end
      else
        redirect_to stock_path(stock.id), alert: 'Insufficient funds'
      end
    else
      redirect_to stock_path(stock.id), alert: 'Invalid input'
    end
  end

  def sell
    stock = Stock.find(params[:id])
    quantity = params[:transaction][:quantity].to_i
    amount = stock.price * quantity
    if quantity > 0
      if @portfolio[stock.id] && @portfolio[stock.id] > quantity
        @transaction =
          current_user.transactions.new(
            transaction_params.merge(
              action: 'sale',
              stock_id: stock.id,
              price: stock.price,
              amount: amount,
            ),
          )

        if @transaction.save
          redirect_to stock_path(stock.id), notice: 'Sold stock'
        else
          redirect_to stock_path(stock.id), alert: 'Error'
        end
      else
        redirect_to stock_path(stock.id), alert: 'Insufficient stock'
      end
    else
      redirect_to stock_path(stock.id), alert: 'Invalid input'
    end
  end

  private

  def transaction_params
    params.require(:transaction).permit(:action, :amount, :quantity)
  end

  def set_portfolio
    portfolio = {}

    transactions = Transaction.where(user_id: current_user.id)
    transactions.each do |transaction|
      portfolio[transaction.stock_id] = 0 if !portfolio[transaction.stock_id] &&
        transaction.action != 'cash in'
      portfolio[transaction.stock_id] += transaction.quantity if transaction
        .action == 'purchase'
      portfolio[transaction.stock_id] -= transaction.quantity if transaction
        .action == 'sale'
    end

    @portfolio = portfolio
  end

  def set_balance
    @balance = Transaction.where(user_id: current_user.id).pluck(:amount).sum
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/cashin.html.erb
<div class='centered-body'>
  <%= link_to account_path do %>
    <%= image_tag('back.svg') %>
  <% end %>
  <div class='card flex-column-10px-gap'>
    <div class='header'>Add funds to wallet</div>
    <%= form_with model: @transaction, url: cashin_post_path do |f| %>
      <div class='flex-column-20px-gap'>
        <div class='flex-column-5px-gap'>
          <div>
            <%= f.label :amount %>
            <%= f.number_field :amount, step: 0.01, autofocus: true %>
          </div>
          <% @transaction.errors.full_messages_for(:amount).each do |message| %>
            <div class='error-message'>
              <%= message %>
            </div>
          <% end %>
        </div>
        <div>
          <%= f.submit 'Add funds', class: 'button-primary' %>
        </div>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/transactions/index.html.erb
<div class='centered-body'>
  <div class='header'>Transactions</div>
  <% if @transactions.length > 0 %>
    <div class='card'>
      <table>
        <tr>
          <% if current_user.admin %>
            <th>User</th>
          <% end %>
          <th>Action</th>
          <th>Amount</th>
          <th>Stock</th>
          <th>Quantity</th>
          <th>Price</th>
        </tr>
        <% @transactions.each do |transaction| %>
          <tr>
            <% if current_user.admin %>
              <td>
                <%= "#{transaction.user.first_name} #{transaction.user.last_name}" %>
              </td>
            <% end %>
            <td>
              <%= transaction.action.capitalize %>
            </td>
            <% if transaction.amount >= 0 %>
              <td class='green'>
                <%= number_to_currency(transaction.amount, format: '%u %n') %>
              </td>
            <% else %>
              <td class='red'>
                <%= number_to_currency(transaction.amount.abs, format: '%u %n') %>
              </td>
            <% end %>
            <td>
              <% if transaction.stock_id %>
                <%= Stock.find(transaction.stock_id).symbol %>
              <% end %>
            </td>
            <td>
              <%= transaction.quantity.to_i == transaction.quantity ? transaction.quantity.to_i : transaction.quantity %>
            </td>
            <td>
              <%= number_to_currency(transaction.price, format: '%u %n') %>
            </td>
          </div>
        <% end %>
      </table>
    </div>
  <% else %>
    <%= render 'pages/empty' %>
  <% end %>
</div>