config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#home'
  get '/portfolio', to: 'pages#portfolio', as: 'portfolio'
  get '/account', to: 'pages#account', as: 'account'
  get '/blocked', to: 'pages#blocked', as: 'blocked'

  get '/transactions', to: 'transactions#index', as: 'transactions'
  get '/cashin', to: 'transactions#cashin', as: 'cashin'
  post '/cashin', to: 'transactions#cashin_post', as: 'cashin_post'
  post '/buy/:id', to: 'transactions#buy', as: 'buy'
  post '/sell/:id', to: 'transactions#sell', as: 'sell'

  get '/users', to: 'users#index', as: 'users'
  get '/pending', to: 'users#pending', as: 'pending'
  get '/users/new', to: 'users#new', as: 'new_user'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  post '/users/create', to: 'users#create', as: 'create_user'
  patch '/users/:id/update', to: 'users#update', as: 'update_user'
  patch '/users/:id/approve', to: 'users#approve', as: 'approve_user'

  get '/stocks', to: 'stocks#index', as: 'stocks'
  get '/stocks/:id', to: 'stocks#show', as: 'stock'
  post '/stocks/create', to: 'stocks#create', as: 'create_stock'
  patch '/stocks/:id/update', to: 'stocks#update', as: 'update_stock'
end

app/views/layouts/_navbar.html.erb
<div class='navbar'>
  <div class='navleft'>
    <div class='logo'>
      <%= link_to 'banana', root_path %>
    </div>
    <div class='navlinks'>
      <% if user_signed_in? %>
        <% if current_user.admin %>
          <%= link_to 'Users', users_path, class: @selected == 'users' ? 'selected' : nil %>
          <%= link_to 'Pending', pending_path, class: @selected == 'pending' ? 'selected' : nil %>
        <% else %>
          <%= link_to 'Stocks', stocks_path, class: @selected == 'stocks' ? 'selected' : nil %>
          <%= link_to 'Portfolio', portfolio_path, class: @selected == 'portfolio' ? 'selected' : nil %>
          <%= link_to 'Account', account_path, class: @selected == 'account' ? 'selected' : nil %>
        <% end %>
        <%= link_to 'Transactions', transactions_path, class: @selected == 'transactions' ? 'selected' : nil %>
      <% end %>
    </div>
  </div>
  <div class='navright'>
    <% if user_signed_in? %>
      <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: 'button-secondary' %>
    <% else %>
      <%= button_to 'Sign in', user_session_path, class: 'button-primary' %>
    <% end %>
  </div>
</div>

app/views/layouts/_toasts.html.erb
<% if notice %>
  <div class='toast notice'>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class='toast alert'>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>banana</title>
    <meta name='viewport' content='width=device-width,initial-scale=1'>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('doodle-146.svg') %>
  </head>
  <body>
    <% if user_signed_in? %>
      <%= render 'layouts/navbar' %>
      <div class='body'>
        <%= yield %>
      </div>
    <% else %>
      <%= yield %>
    <% end %>
    <%= render 'layouts/toasts' %>
  </body>
</html>